import 'dart:convert';
import 'dart:io';
import 'dart:typed_data';
import 'dart:ui' as ui;

import 'package:flutter_test/flutter_test.dart';
import 'package:piketemaker/core/recolor/opencv_lab.dart';
import 'package:piketemaker/core/recolor/recolor_region.dart';
import 'package:piketemaker/core/segmentation/garment_segmenter.dart';
import 'package:piketemaker/core/segmentation/mask_hardening.dart';
import 'package:piketemaker/core/segmentation/mediapipe_garment_segmenter.dart';
import 'package:piketemaker/core/segmentation/recolor_applicability.dart';

/// PYTHON PARITY of the I2 recolor engine (D38, pass 1).
///
/// Fixture: `recolor_parity_I2.json`, generated by
/// `cv_core/tools/gen_recolor_fixtures_dart.py` from the canonical
/// `colorlab.segmentation` (C1 hardening + applicability) and
/// `colorlab.recolor.recolor_region`. Synthetic scenes only.
///
/// Tolerances (and why):
///  - hardening / split / hip row / components: EXACT (integer logic);
///  - smoothed resample: <= [_kResampleMaxMismatch] of the pixels may differ
///    (float32 bilinear + blur in OpenCV vs float64 accumulation here could
///    flip an exact argmax tie on a contour). ACHIEVED: 0 mismatches on all
///    three cases, including the app-sized 256 -> 384x512 upscale;
///  - applicability: same reason + region verdicts, metrics within 1e-9
///    (integer ratios) or 0.5 L* (the light statistics — OpenCV's float
///    RGB->Lab is a LUT approximation, see [OpenCvLab]);
///  - recolor: max |ΔRGB| <= [_kRecolorMaxDelta] and mean <= [_kRecolorMeanDelta]
///    inside the mask, outside the mask BYTE-IDENTICAL. ACHIEVED (2026-09-30):
///    max 1 on six cases, 3 on one (hue replacement with an explicit source:
///    the source's LUT-vs-formula LAB offset moves the gain/chroma scale of
///    every pixel a little), mean 0.06-0.22.
const double _kResampleMaxMismatch = 0.001;
const int _kRecolorMaxDelta = 3;
const double _kRecolorMeanDelta = 0.25;
const double _kLightMetricTolerance = 0.5;

Map<String, dynamic> _load() {
  final File file = File('test/core/fixtures/recolor_parity_I2.json');
  if (!file.existsSync()) {
    fail('recolor_parity_I2.json does not exist. Regenerate with: '
        '.venv/Scripts/python.exe cv_core/tools/gen_recolor_fixtures_dart.py '
        '(from the repo root).');
  }
  return jsonDecode(file.readAsStringSync()) as Map<String, dynamic>;
}

Future<Uint8List> _decodeRgba(String b64) async {
  final ui.Codec codec = await ui.instantiateImageCodec(base64Decode(b64));
  final ui.Image image = (await codec.getNextFrame()).image;
  final ByteData? data =
      await image.toByteData(format: ui.ImageByteFormat.rawRgba);
  final Uint8List rgba = Uint8List.fromList(data!.buffer.asUint8List());
  image.dispose();
  codec.dispose();
  return rgba;
}

/// Grayscale PNG -> one byte per pixel (the value is in every channel).
Future<Uint8List> _decodeGray(String b64) async {
  final Uint8List rgba = await _decodeRgba(b64);
  final Uint8List out = Uint8List(rgba.length ~/ 4);
  for (int i = 0; i < out.length; i++) {
    out[i] = rgba[i * 4];
  }
  return out;
}

Future<Uint8List> _map(Map<String, dynamic> payload) async {
  final Uint8List map = await _decodeGray(payload['png'] as String);
  int sum = 0;
  for (final int v in map) {
    sum += v;
  }
  expect(sum, payload['sum'], reason: 'class-map PNG transport');
  expect(map.length, (payload['width'] as int) * (payload['height'] as int));
  return map;
}

Future<Uint8List> _mask(Map<String, dynamic> payload) async {
  final Uint8List mask = await _decodeGray(payload['png'] as String);
  expect(maskCount(mask), payload['count'], reason: 'mask PNG transport');
  return mask;
}

int maskCount(Uint8List mask) {
  int c = 0;
  for (final int v in mask) {
    if (v != 0) c++;
  }
  return c;
}

Future<Uint8List> _rgba(Map<String, dynamic> payload) async {
  final Uint8List rgba = await _decodeRgba(payload['png'] as String);
  final List<int> sums = <int>[0, 0, 0];
  for (int i = 0; i < rgba.length; i += 4) {
    sums[0] += rgba[i];
    sums[1] += rgba[i + 1];
    sums[2] += rgba[i + 2];
  }
  expect(sums,
      <int>[for (final dynamic s in payload['sums'] as List<dynamic>) s as int],
      reason: 'RGB PNG transport');
  return rgba;
}

int _mismatches(Uint8List a, Uint8List b) {
  expect(a.length, b.length);
  int n = 0;
  for (int i = 0; i < a.length; i++) {
    if (a[i] != b[i]) n++;
  }
  return n;
}

Future<void> _expectRegions(Map<String, dynamic> expected,
    HardenedSplit? Function() split, String label) async {
  if (expected['no_person'] as bool) {
    expect(split, throwsA(isA<SegmentationException>()), reason: label);
    return;
  }
  final HardenedSplit got = split()!;
  final Map<String, dynamic> regions =
      expected['regions'] as Map<String, dynamic>;
  expect(got.masks.keys.map((GarmentRegion r) => r.name).toList(),
      regions.keys.toList(),
      reason: '$label: surviving regions');
  for (final MapEntry<String, dynamic> entry in regions.entries) {
    final GarmentRegion region = GarmentRegion.values.byName(entry.key);
    final Uint8List want = await _mask(entry.value as Map<String, dynamic>);
    expect(_mismatches(got.masks[region]!, want), 0,
        reason: '$label: ${entry.key} mask');
  }
}

void main() {
  final Map<String, dynamic> fixture = _load();

  test('class ids mirror Python and the segmenter', () {
    expect(SegClass.background, MediaPipeGarmentSegmenter.backgroundClassIndex);
    expect(SegClass.hair, MediaPipeGarmentSegmenter.hairClassIndex);
    expect(SegClass.bodySkin, MediaPipeGarmentSegmenter.bodySkinClassIndex);
    expect(SegClass.faceSkin, MediaPipeGarmentSegmenter.faceSkinClassIndex);
    expect(SegClass.clothes, MediaPipeGarmentSegmenter.clothesClassIndex);
    expect(SegClass.others, MediaPipeGarmentSegmenter.othersClassIndex);
    expect(SegClass.count, MediaPipeGarmentSegmenter.numClasses);
  });

  group('LAB (OpenCV float convention)', () {
    final Map<String, dynamic> lab = fixture['lab'] as Map<String, dynamic>;

    test('RGB -> LAB within the OpenCV LUT error', () {
      final Map<String, dynamic> probes =
          lab['rgb_to_lab'] as Map<String, dynamic>;
      final List<dynamic> rgbs = probes['rgb'] as List<dynamic>;
      final List<dynamic> labs = probes['lab'] as List<dynamic>;
      for (int i = 0; i < rgbs.length; i++) {
        final List<int> rgb = (rgbs[i] as List<dynamic>).cast<int>();
        final List<double> got = OpenCvLab.labOf(rgb);
        final List<dynamic> want = labs[i] as List<dynamic>;
        for (int c = 0; c < 3; c++) {
          expect((got[c] - (want[c] as num)).abs(), lessThan(0.5),
              reason: 'rgb $rgb channel $c: $got vs $want');
        }
      }
    });

    test('LAB -> RGB matches OpenCV to one 8-bit step', () {
      final Map<String, dynamic> probes =
          lab['lab_to_rgb'] as Map<String, dynamic>;
      final List<dynamic> labs = probes['lab'] as List<dynamic>;
      final List<dynamic> rgbs = probes['rgb'] as List<dynamic>;
      final Float64List out = Float64List(3);
      int exact = 0;
      for (int i = 0; i < labs.length; i++) {
        final List<dynamic> l = labs[i] as List<dynamic>;
        OpenCvLab.labToRgbFloat((l[0] as num).toDouble(),
            (l[1] as num).toDouble(), (l[2] as num).toDouble(), out);
        final List<dynamic> want = rgbs[i] as List<dynamic>;
        bool same = true;
        for (int c = 0; c < 3; c++) {
          final int got = OpenCvLab.to8bit(out[c]);
          expect((got - (want[c] as int)).abs(), lessThanOrEqualTo(1));
          same &= got == want[c];
        }
        if (same) exact++;
      }
      expect(exact, greaterThanOrEqualTo(labs.length - 2),
          reason: 'the inverse is the same formula: almost all exact');
    });
  });

  group('smoothed resample (resample_class_map_smooth)', () {
    for (final dynamic raw in fixture['resample'] as List<dynamic>) {
      final Map<String, dynamic> c = raw as Map<String, dynamic>;
      test(c['name'] as String, () async {
        final Map<String, dynamic> input = c['input'] as Map<String, dynamic>;
        final Uint8List src = await _map(input);
        final Uint8List want =
            await _map(c['expected'] as Map<String, dynamic>);
        final Uint8List got = resampleClassMapSmooth(
          src,
          input['width'] as int,
          input['height'] as int,
          c['target_width'] as int,
          c['target_height'] as int,
        );
        final int bad = _mismatches(got, want);
        expect(bad / want.length, lessThanOrEqualTo(_kResampleMaxMismatch),
            reason: '$bad / ${want.length} pixels differ');
      });
    }
  });

  group('hardening (harden_class_map + split)', () {
    for (final dynamic raw in fixture['harden'] as List<dynamic>) {
      final Map<String, dynamic> c = raw as Map<String, dynamic>;
      final String name = c['name'] as String;
      test(name, () async {
        final Map<String, dynamic> input = c['input'] as Map<String, dynamic>;
        final int w = input['width'] as int;
        final int h = input['height'] as int;
        final Uint8List map = await _map(input);

        expect(
            _mismatches(fillClothesHoles(map, w, h),
                await _mask(c['fill_clothes_holes'] as Map<String, dynamic>)),
            0,
            reason: 'fill_clothes_holes');
        expect(
            _mismatches(
                dropDetachedClothes(map, w, h),
                await _mask(
                    c['drop_detached_clothes'] as Map<String, dynamic>)),
            0,
            reason: 'drop_detached_clothes');
        expect(
            _mismatches(hardenClassMap(map, w, h, kDefaultHardening),
                await _map(c['harden_default'] as Map<String, dynamic>)),
            0,
            reason: 'harden (default)');
        final Uint8List recolorMap =
            hardenClassMap(map, w, h, kRecolorHardening);
        expect(
            _mismatches(recolorMap,
                await _map(c['harden_recolor'] as Map<String, dynamic>)),
            0,
            reason: 'harden (recolor)');

        Uint8List clothesOf(Uint8List m) => Uint8List.fromList(<int>[
              for (final int v in m) v == SegClass.clothes ? 1 : 0,
            ]);
        final Map<String, dynamic> rawSplit =
            c['hip_split_raw'] as Map<String, dynamic>;
        final ({int row, bool fromWaist}) gotRaw =
            hipSplitRow(clothesOf(map), w, h);
        expect(gotRaw.row, rawSplit['row']);
        expect(gotRaw.fromWaist, rawSplit['from_waist']);
        final Map<String, dynamic> recSplit =
            c['hip_split_recolor'] as Map<String, dynamic>;
        final ({int row, bool fromWaist}) gotRec =
            hipSplitRow(clothesOf(recolorMap), w, h);
        expect(gotRec.row, recSplit['row']);
        expect(gotRec.fromWaist, recSplit['from_waist']);

        await _expectRegions(
            c['split_recolor'] as Map<String, dynamic>,
            () => splitHardenedGarmentMasks(map, w, h, erodePx: 0),
            'split_recolor');
        await _expectRegions(c['split_recolor_eroded'] as Map<String, dynamic>,
            () => splitHardenedGarmentMasks(map, w, h), 'split_recolor_eroded');
      });
    }
  });

  group('applicability (check_applicability)', () {
    for (final dynamic raw in fixture['applicability'] as List<dynamic>) {
      final Map<String, dynamic> c = raw as Map<String, dynamic>;
      test(c['name'] as String, () async {
        final Map<String, dynamic> mapPayload =
            c['class_map'] as Map<String, dynamic>;
        final int w = mapPayload['width'] as int;
        final int h = mapPayload['height'] as int;
        final Uint8List map = await _map(mapPayload);
        final Uint8List rgba = await _rgba(c['rgb'] as Map<String, dynamic>);
        Map<GarmentRegion, Uint8List> regions = <GarmentRegion, Uint8List>{};
        try {
          regions = splitHardenedGarmentMasks(map, w, h, erodePx: 0).masks;
        } on SegmentationException {
          regions = <GarmentRegion, Uint8List>{};
        }
        expect(regions.keys.map((GarmentRegion r) => r.name).toList(),
            c['region_names']);
        final RecolorApplicability got =
            checkRecolorApplicability(map, w, h, rgba: rgba, regions: regions);
        expect(got.reason == null ? null : recolorBlockerId(got.reason!),
            c['reason']);
        final Map<String, dynamic> wantRegions =
            c['regions'] as Map<String, dynamic>;
        expect(got.regions.length, wantRegions.length);
        for (final MapEntry<String, dynamic> e in wantRegions.entries) {
          final RecolorBlocker? r =
              got.regions[GarmentRegion.values.byName(e.key)];
          expect(r == null ? null : recolorBlockerId(r), e.value,
              reason: 'region ${e.key}');
        }
        final Map<String, dynamic> wantMetrics =
            c['metrics'] as Map<String, dynamic>;
        expect(got.metrics.keys.toSet(), wantMetrics.keys.toSet());
        for (final MapEntry<String, dynamic> e in wantMetrics.entries) {
          final double tol =
              e.key.endsWith('_l') ? _kLightMetricTolerance : 1e-9;
          expect((got.metrics[e.key]! - (e.value as num)).abs(),
              lessThanOrEqualTo(tol),
              reason: '${e.key}: ${got.metrics[e.key]} vs ${e.value}');
        }
      });
    }
  });

  group('recolor_region', () {
    final Map<String, dynamic> section =
        fixture['recolor'] as Map<String, dynamic>;
    for (final dynamic raw in section['cases'] as List<dynamic>) {
      final Map<String, dynamic> c = raw as Map<String, dynamic>;
      test(c['name'] as String, () async {
        final Map<String, dynamic> photos =
            section['photos'] as Map<String, dynamic>;
        final Map<String, dynamic> photoPayload =
            photos[c['photo'] as String] as Map<String, dynamic>;
        final int w = photoPayload['width'] as int;
        final int h = photoPayload['height'] as int;
        final Uint8List photo = await _rgba(photoPayload);
        final Uint8List mask =
            await _mask(section['mask'] as Map<String, dynamic>);
        final Uint8List want =
            await _rgba(c['expected'] as Map<String, dynamic>);
        final List<dynamic>? source = c['source'] as List<dynamic>?;
        final Uint8List got = recolorRegion(
          photo,
          w,
          h,
          mask,
          (c['target'] as List<dynamic>).cast<int>(),
          sourceRgb: source?.cast<int>(),
          featherPx: (c['feather_px'] as int?) ?? kRecolorFeatherPx,
          lightnessShift: (c['lightness_shift'] as num?)?.toDouble(),
          selective: c['selective'] as bool,
        );
        int maxDelta = 0;
        int sumDelta = 0;
        int inside = 0;
        for (int i = 0; i < w * h; i++) {
          for (int ch = 0; ch < 4; ch++) {
            final int d = (got[i * 4 + ch] - want[i * 4 + ch]).abs();
            if (mask[i] == 0) {
              expect(d, 0, reason: 'outside the mask must be byte-identical');
              expect(got[i * 4 + ch], photo[i * 4 + ch]);
            } else if (ch < 3) {
              if (d > maxDelta) maxDelta = d;
              sumDelta += d;
            }
          }
          if (mask[i] != 0) inside++;
        }
        final double mean = sumDelta / (inside * 3);
        expect(maxDelta, lessThanOrEqualTo(_kRecolorMaxDelta),
            reason: 'max |dRGB| $maxDelta (mean $mean)');
        expect(mean, lessThanOrEqualTo(_kRecolorMeanDelta),
            reason: 'mean |dRGB| $mean');
        // Something actually changed inside the mask.
        expect(_mismatches(got, photo), greaterThan(inside ~/ 2));
      });
    }
  });
}
