import 'dart:convert';
import 'dart:io';

import 'package:flutter_test/flutter_test.dart';
import 'package:piketemaker/core/color_engine/borders.dart';
import 'package:piketemaker/core/color_engine/harmony.dart';

/// PYTHON PARITY for the optional #48 border-background layer (issue #49).
///
/// Verifies the Dart port in `borders.dart` against the EXACT output of the
/// canonical `cv_core/colorlab.borders`. The fixture `border_bg_D48.json` is
/// generated by `cv_core/tools/gen_border_fixtures_dart.py` (venv at the repo
/// root) and contains, per case, the exact input pixels/palette and the
/// candidates/base colorlab produced. Same tolerance philosophy as the palette
/// fixtures: K-means-derived candidate colors compared with an RGB atol; the
/// pure demotion logic compared exactly by index.
///
/// Fixture file name and JSON keys are FROZEN (generated from Python): do not
/// rename them here.

Map<String, dynamic> _load(String name) {
  final File file = File('test/core/fixtures/$name');
  if (!file.existsSync()) {
    fail('$name does not exist. Regenerate with: '
        '.venv/bin/python cv_core/tools/gen_border_fixtures_dart.py '
        '(from the repo root).');
  }
  return jsonDecode(file.readAsStringSync()) as Map<String, dynamic>;
}

List<int> _rgb(dynamic value) =>
    <int>[for (final dynamic c in value as List<dynamic>) (c as num).toInt()];

/// Flat row-major RGB (r, g, b, r, g, b, ...) from a list of [r, g, b] triplets.
List<int> _flatRgb(List<dynamic> pixels) {
  final List<int> out = List<int>.filled(pixels.length * 3, 0);
  for (int i = 0; i < pixels.length; i++) {
    final List<dynamic> px = pixels[i] as List<dynamic>;
    for (int d = 0; d < 3; d++) {
      out[i * 3 + d] = (px[d] as num).toInt();
    }
  }
  return out;
}

BackgroundCandidate _candidate(Map<String, dynamic> j) => BackgroundCandidate(
      origin: j['origin'] as String,
      color: _rgb(j['color']),
      coverage: (j['coverage'] as num).toDouble(),
    );

void main() {
  final Map<String, dynamic> f = _load('border_bg_D48.json');
  final double atolRgb = (f['atol_rgb'] as num).toDouble();
  final double atolCoverage = (f['atol_coverage'] as num).toDouble();

  test('constants mirror colorlab.borders 1:1', () {
    expect(kBorderBandFraction, (f['band_fraction'] as num).toDouble());
    expect(
        kBorderSimilarityDeltaE, (f['similarity_delta_e'] as num).toDouble());
    expect(kBorderCoverageMin, (f['coverage_min'] as num).toDouble());
    expect(kBorderBandClusters, f['border_band_clusters'] as int);
  });

  group('estimateBackgroundCandidates parity with colorlab', () {
    for (final dynamic caseDyn in f['estimate_cases'] as List<dynamic>) {
      final Map<String, dynamic> c = caseDyn as Map<String, dynamic>;
      test(c['nombre'] as String, () {
        final int height = c['height'] as int;
        final int width = c['width'] as int;
        final List<int> rgb = _flatRgb(c['pixeles'] as List<dynamic>);

        final List<BackgroundCandidate> got =
            estimateBackgroundCandidates(rgb, height, width);
        final List<dynamic> expected =
            c['esperado_candidatos'] as List<dynamic>;

        expect(got.length, expected.length,
            reason: 'candidate count differs from Python');
        for (int i = 0; i < expected.length; i++) {
          final Map<String, dynamic> e = expected[i] as Map<String, dynamic>;
          // Origin and ORDER (wall before floor) must match exactly.
          expect(got[i].origin, e['origin'], reason: 'candidate $i origin');
          final List<int> eColor = _rgb(e['color']);
          for (int d = 0; d < 3; d++) {
            expect(got[i].color[d], closeTo(eColor[d], atolRgb),
                reason: 'candidate $i color: ${got[i].color} vs $eColor');
          }
          expect(got[i].coverage,
              closeTo((e['coverage'] as num).toDouble(), atolCoverage),
              reason: 'candidate $i coverage');
        }
      });
    }
  });

  group('pickHarmonyBaseAvoidingBackground parity with colorlab', () {
    for (final dynamic caseDyn in f['pick_cases'] as List<dynamic>) {
      final Map<String, dynamic> c = caseDyn as Map<String, dynamic>;
      test(c['nombre'] as String, () {
        final List<List<int>> colors = <List<int>>[
          for (final dynamic col in c['colores'] as List<dynamic>) _rgb(col),
        ];
        final List<double> weights = <double>[
          for (final dynamic w in c['pesos'] as List<dynamic>)
            (w as num).toDouble(),
        ];
        final List<BackgroundCandidate> candidates = <BackgroundCandidate>[
          for (final dynamic j in c['candidatos'] as List<dynamic>)
            _candidate(j as Map<String, dynamic>),
        ];

        // The baseline (no layer) index must match Python's baseline.
        expect(pickHarmonyBase(colors, weights), c['baseline_indice'] as int,
            reason: 'baseline index');

        final int index =
            pickHarmonyBaseAvoidingBackground(colors, weights, candidates);
        expect(index, c['esperado_indice'] as int, reason: 'chosen index');

        // The chosen palette color must equal Python's chosen base RGB.
        if (index >= 0) {
          expect(colors[index], _rgb(c['esperado_base']),
              reason: 'chosen base color');
        }

        // The palette and weights are never modified by the layer.
        final List<List<int>> colorsBefore = <List<int>>[
          for (final List<int> col in colors) List<int>.of(col)
        ];
        final List<double> weightsBefore = List<double>.of(weights);
        pickHarmonyBaseAvoidingBackground(colors, weights, candidates);
        expect(colors, colorsBefore, reason: 'palette must not be modified');
        expect(weights, weightsBefore, reason: 'weights must not be modified');
      });
    }
  });

  test('empty candidates keep the baseline pick (layer inert)', () {
    // Same wallish palette as the fixture, but with no candidates at all.
    final List<List<int>> colors = <List<int>>[
      <int>[200, 180, 150],
      <int>[110, 130, 160],
    ];
    final List<double> weights = <double>[0.75, 0.25];
    expect(
      pickHarmonyBaseAvoidingBackground(
          colors, weights, const <BackgroundCandidate>[]),
      pickHarmonyBase(colors, weights),
    );
  });
}
