import 'dart:convert';
import 'dart:io';
import 'dart:typed_data';
import 'dart:ui' as ui;

import 'package:flutter_test/flutter_test.dart';
import 'package:piketemaker/core/color_engine/borders.dart';
import 'package:piketemaker/core/color_engine/color_engine.dart';
import 'package:piketemaker/core/color_engine/color_engine_dart.dart';
import 'package:piketemaker/core/color_engine/models.dart';
import 'package:piketemaker/core/segmentation/garment_segmenter.dart';

/// PYTHON PARITY + flag gating for D24 product mode (feature F11), including
/// the #84 layers landed at the gate G2S review.
///
/// Three things are verified per fixture case:
///
///  1. #84 DIAGNOSTIC PARITY: [estimateMultiedgeBackground] finds the same
///     background colors as `colorlab.borders.estimate_multiedge_background`
///     and [productBackgroundMask] drops the same fraction of the frame
///     (including the 0.0 of the frame-filling guardrail case).
///
///  2. END-TO-END PARITY: the exact product composition the engine runs —
///     [extractProductPixels] (multi-edge drop before clustering) +
///     `buildResult(productMode: true)` (neutral-lightness merge protection)
///     — matches the EXACT output of
///     `colorlab.pipeline.analyze_palette(product_mode=True)` on the same
///     pixels. The fixture `product_mode_D24.json` is generated by
///     `cv_core/tools/gen_product_fixtures_dart.py` (venv at the repo root).
///     Same tolerance philosophy as the palette fixtures (RGB atol; the
///     harmony arithmetic exact via the base).
///
///  3. FLAG GATING: `ColorEngineDart(productMode: true)` BYPASSES the garment
///     segmenter AND suppresses a wrapping studio background, while the
///     default outfit engine still invokes the segmenter.
///
/// Fixture file name and JSON keys are FROZEN (generated from Python): do not
/// rename them here.

/// Fraction tolerance for the suppressed-pixel diagnostic: the mask is a hard
/// per-pixel rule over K-means-derived colors, so tiny center drift can move a
/// handful of boundary pixels.
const double _atolFraction = 0.02;

Map<String, dynamic> _load(String name) {
  final File file = File('test/core/fixtures/$name');
  if (!file.existsSync()) {
    fail('$name does not exist. Regenerate with: '
        '.venv/Scripts/python.exe cv_core/tools/gen_product_fixtures_dart.py '
        '(from the repo root).');
  }
  return jsonDecode(file.readAsStringSync()) as Map<String, dynamic>;
}

/// Flat row-major RGB (r, g, b, ...) from the fixture's [r, g, b] triplets.
List<int> _flatRgb(List<dynamic> pixels) {
  final List<int> out = List<int>.filled(pixels.length * 3, 0);
  for (int i = 0; i < pixels.length; i++) {
    final List<dynamic> px = pixels[i] as List<dynamic>;
    for (int d = 0; d < 3; d++) {
      out[i * 3 + d] = (px[d] as num).toInt();
    }
  }
  return out;
}

/// Opaque RGBA buffer from the fixture pixels — the exact input shape
/// [extractProductPixels] receives from the decoder.
Uint8List _rgba(List<dynamic> pixels) {
  final Uint8List out = Uint8List(pixels.length * 4);
  for (int i = 0; i < pixels.length; i++) {
    final List<dynamic> px = pixels[i] as List<dynamic>;
    for (int d = 0; d < 3; d++) {
      out[i * 4 + d] = (px[d] as num).toInt();
    }
    out[i * 4 + 3] = 0xFF;
  }
  return out;
}

List<int> _rgb(dynamic value) =>
    <int>[for (final dynamic c in value as List<dynamic>) (c as num).toInt()];

List<int> _channels(ui.Color color) {
  // ignore: deprecated_member_use  (Color.value: universal across Flutter 3.19+)
  final int value = color.value;
  return <int>[(value >> 16) & 0xFF, (value >> 8) & 0xFF, value & 0xFF];
}

bool _within(List<int> a, List<int> b, double atol) {
  for (int d = 0; d < 3; d++) {
    if ((a[d] - b[d]).abs() > atol) {
      return false;
    }
  }
  return true;
}

/// A segmenter tripwire: throws if invoked. Product mode must never call it.
class _ThrowingSegmenter implements GarmentSegmenter {
  const _ThrowingSegmenter();

  @override
  Future<GarmentSegmentation> segment(
      Uint8List rgba, int width, int height) async {
    throw StateError('segmenter must not run: product mode should bypass it');
  }
}

/// 60x60 PNG: a red product blob on a gray studio wall, no antialiasing. The
/// gray wraps all four edges, so #84 must suppress it.
Future<Uint8List> _productPng() async {
  final ui.PictureRecorder recorder = ui.PictureRecorder();
  final ui.Canvas canvas = ui.Canvas(recorder);
  final ui.Paint paint = ui.Paint()..isAntiAlias = false;
  paint.color = const ui.Color(0xFFCDCDCD); // gray (205, 205, 205)
  canvas.drawRect(const ui.Rect.fromLTWH(0, 0, 60, 60), paint);
  paint.color = const ui.Color(0xFFC82828); // red (200, 40, 40)
  canvas.drawRect(const ui.Rect.fromLTWH(15, 15, 30, 30), paint);
  final ui.Image image = await recorder.endRecording().toImage(60, 60);
  final ByteData? png = await image.toByteData(format: ui.ImageByteFormat.png);
  image.dispose();
  return png!.buffer.asUint8List(png.offsetInBytes, png.lengthInBytes);
}

void main() {
  TestWidgetsFlutterBinding.ensureInitialized();

  group('product-mode parity with colorlab (D24 + #84)', () {
    final Map<String, dynamic> f = _load('product_mode_D24.json');
    for (final dynamic caseDyn in f['cases'] as List<dynamic>) {
      final Map<String, dynamic> c = caseDyn as Map<String, dynamic>;
      test(c['nombre'] as String, () {
        final Map<String, dynamic> expected =
            c['esperado'] as Map<String, dynamic>;
        final double atolRgb = (c['atol_rgb'] as num).toDouble();
        final double atolWeight = (c['atol_peso'] as num).toDouble();
        final int height = c['height'] as int;
        final int width = c['width'] as int;
        final List<dynamic> pixelTriplets = c['pixeles'] as List<dynamic>;
        final List<int> rgb = _flatRgb(pixelTriplets);
        final Uint8List rgba = _rgba(pixelTriplets);

        // --- Stage 1 (#84 diagnostics): background estimate + drop fraction.
        final List<dynamic> expectedBg =
            expected['bg_colores'] as List<dynamic>;
        final List<List<int>> gotBg =
            estimateMultiedgeBackground(rgb, height, width);
        expect(gotBg.length, expectedBg.length,
            reason: 'multi-edge background color count differs from Python: '
                '$gotBg vs $expectedBg');
        for (final dynamic e in expectedBg) {
          final List<int> expectedColor = _rgb(e);
          expect(
            gotBg.any((List<int> g) => _within(g, expectedColor, atolRgb)),
            isTrue,
            reason: 'background color $expectedColor not found in $gotBg',
          );
        }
        final List<bool> mask = productBackgroundMask(rgb, height, width);
        final double fraction = mask.where((bool d) => d).length / mask.length;
        expect(
            fraction,
            closeTo(
                (expected['frac_supresion'] as num).toDouble(), _atolFraction),
            reason: 'suppressed fraction (guardrail included)');

        // --- Stage 2 (end to end): the exact composition the engine runs.
        final Float64List pixels = extractProductPixels(rgba, height, width);
        final AnalysisResult res = buildResult(pixels, productMode: true);

        final List<dynamic> expectedColors =
            expected['colores'] as List<dynamic>;
        final List<dynamic> expectedWeights =
            expected['pesos'] as List<dynamic>;
        expect(res.palette.length, expectedColors.length,
            reason: 'color count differs from Python: '
                '${res.palette.map(_paletteHex).toList()} vs $expectedColors');

        for (int i = 0; i < expectedColors.length; i++) {
          final List<int> expectedRgb = _rgb(expectedColors[i]);
          final List<int> got = _channels(res.palette[i].color);
          for (int d = 0; d < 3; d++) {
            expect(got[d], closeTo(expectedRgb[d], atolRgb),
                reason: 'color $i: $got vs $expectedRgb');
          }
          expect(res.palette[i].weight,
              closeTo((expectedWeights[i] as num).toDouble(), atolWeight),
              reason: 'weight $i');
        }

        // D5 base parity (index + chosen RGB); -1 = canvas mode (D10).
        expect(res.baseIndex, expected['indice_base'] as int,
            reason: 'base index');
        if (res.baseIndex >= 0) {
          final List<int> expectedBase = _rgb(expected['base']);
          final List<int> gotBase = _channels(res.base!.color);
          for (int d = 0; d < 3; d++) {
            expect(gotBase[d], closeTo(expectedBase[d], atolRgb),
                reason: 'base color: $gotBase vs $expectedBase');
          }
          // The four harmonies exist and each contains the base.
          expect(res.harmonies, hasLength(4));
          for (final Harmony h in res.harmonies) {
            expect(h.colors, contains(res.base!.color));
          }
        } else {
          // Canvas mode: curated pops, no harmonies (D10).
          expect(res.harmonies, isEmpty);
          expect(res.canvasAccents, hasLength(kCanvasAccentCount));
        }
      });
    }
  });

  group('productMode flag gates the #84 layers and the segmenter bypass', () {
    test('product mode suppresses the wrapping studio background (#84)',
        () async {
      const ColorEngineDart engine = ColorEngineDart(
        segmenter: _ThrowingSegmenter(), // also proves the bypass
        productMode: true,
      );
      final AnalysisResult res = await engine.analyze(await _productPng());
      // The gray (205,205,205) wraps all 4 edges -> suppressed: the palette
      // is the red product alone and the base is that red.
      expect(res.baseIndex, 0);
      final List<int> base = _channels(res.base!.color);
      expect(_within(base, <int>[200, 40, 40], 12.0), isTrue,
          reason: 'base should be the red product, got $base');
      for (final ColorSample s in res.palette) {
        expect(_within(_channels(s.color), <int>[205, 205, 205], 12.0), isFalse,
            reason: 'a studio-gray swatch survived: ${_paletteHex(s)}');
      }
    });

    test('outfit mode (default) DOES invoke the segmenter', () async {
      // The tripwire fires and the decode step wraps it as a
      // ColorEngineException whose message carries the segmenter's text — proof
      // the segmenter WAS reached (the opposite of the product-mode bypass).
      const ColorEngineDart engine =
          ColorEngineDart(segmenter: _ThrowingSegmenter());
      await expectLater(
        engine.analyze(await _productPng()),
        throwsA(isA<ColorEngineException>().having(
          (ColorEngineException e) => e.reason,
          'reason',
          contains('segmenter must not run'),
        )),
      );
    });
  });
}

String _paletteHex(ColorSample s) => s.hex;

/// The curated canvas set has 5 accents (D10) — pinned here so the canvas
/// assertion above cannot silently pass on an empty list.
const int kCanvasAccentCount = 5;
