import 'dart:convert';
import 'dart:io';
import 'dart:typed_data';
import 'dart:ui' as ui;

import 'package:flutter_test/flutter_test.dart';
import 'package:piketemaker/core/color_engine/borders.dart';
import 'package:piketemaker/core/color_engine/color_engine_dart.dart';
import 'package:piketemaker/core/color_engine/garments.dart';
import 'package:piketemaker/core/color_engine/models.dart';
import 'package:piketemaker/core/segmentation/garment_segmenter.dart';
import 'package:piketemaker/core/segmentation/mask_hygiene.dart';
import 'package:piketemaker/core/segmentation/mediapipe_garment_segmenter.dart';

/// PYTHON PARITY AT REAL SIZE (BACKLOG B2, code-review finding F7).
///
/// Every other golden fixture is tiny (<= 8000 px), so the engine's fixed-step
/// K-means subsampling ([extractRgbaPixels]: step = ceil(frame / 40k), computed
/// from the WHOLE frame and applied on top of the region mask) never fires
/// there — while the canonical `colorlab` clusters EVERY mask pixel. These
/// cases run at the size the app actually feeds the engine (longest side
/// [kMaxDecodeSide] = 512 -> 196,608 px -> step 5) on textured synthetic
/// content, through the SAME compositions the other parity tests replay:
///
///   per-garment: buildMasks -> applyGarmentGuards -> extractRgbaPixels per
///                region -> buildGarmentAnalysis   (garment_parity_test.dart)
///   product:     extractProductPixels -> buildResult(productMode: true)
///                                                   (product_mode_parity_test.dart)
///
/// Each palette is compared TWICE against Python with the fixture tolerances:
/// once through the engine path (subsampled, what the user gets) and once
/// through a FULL extraction (every mask pixel, the control). If the engine
/// path ever fails while the control passes, the subsampling — not the
/// K-means port — is the culprit.
///
/// Fixture: `parity_real_size_B2.json`, generated by
/// `cv_core/tools/gen_garment_fixtures_dart.py --real-size` (pixels as
/// lossless PNG base64; a channel checksum proves the transport is exact).
/// File name and JSON keys are FROZEN (generated from Python).

Map<String, dynamic> _load() {
  final File file = File('test/core/fixtures/parity_real_size_B2.json');
  if (!file.existsSync()) {
    fail('parity_real_size_B2.json does not exist. Regenerate with: '
        '.venv/Scripts/python.exe cv_core/tools/gen_garment_fixtures_dart.py '
        '--real-size (from the repo root).');
  }
  return jsonDecode(file.readAsStringSync()) as Map<String, dynamic>;
}

/// Decodes a base64 PNG to raw RGBA (the exact buffer the engine's codec
/// hands to the pipeline) and checks its dimensions.
Future<Uint8List> _decodePng(String b64, int width, int height) async {
  final ui.Codec codec = await ui.instantiateImageCodec(base64Decode(b64));
  final ui.Image image = (await codec.getNextFrame()).image;
  expect(image.width, width);
  expect(image.height, height);
  final ByteData? data =
      await image.toByteData(format: ui.ImageByteFormat.rawRgba);
  final Uint8List rgba = Uint8List.fromList(data!.buffer.asUint8List());
  image.dispose();
  codec.dispose();
  return rgba;
}

/// Transport proof: per-channel sums of the decoded RGBA must equal what
/// numpy summed before encoding, and every pixel must be opaque.
void _expectExactTransport(Uint8List rgba, List<dynamic> sums) {
  final List<int> got = <int>[0, 0, 0];
  for (int i = 0; i < rgba.length; i += 4) {
    got[0] += rgba[i];
    got[1] += rgba[i + 1];
    got[2] += rgba[i + 2];
    expect(rgba[i + 3], 0xFF, reason: 'fixture pixels are opaque');
  }
  expect(got, <int>[for (final dynamic s in sums) (s as num).toInt()],
      reason: 'PNG transport is not lossless (channel sums differ)');
}

/// Class map from a grayscale PNG (class id stored in every channel).
Future<Uint8List> _decodeClassMap(
    String b64, int width, int height, List<dynamic> histogram) async {
  final Uint8List rgba = await _decodePng(b64, width, height);
  final Uint8List classes = Uint8List(width * height);
  final List<int> got = List<int>.filled(histogram.length, 0);
  for (int i = 0; i < classes.length; i++) {
    classes[i] = rgba[i * 4];
    expect(rgba[i * 4 + 1], classes[i], reason: 'gray PNG decoded unevenly');
    got[classes[i]] += 1;
  }
  expect(got, <int>[for (final dynamic h in histogram) (h as num).toInt()],
      reason: 'class-map transport is not lossless');
  return classes;
}

/// CONTROL extraction: every opaque pixel of the mask, NO subsampling — what
/// Python clusters. Mirrors [extractRgbaPixels] with step 1.
Float64List _extractAll(Uint8List rgba, {Uint8List? mask}) {
  final int n = rgba.length ~/ 4;
  final List<double> samples = <double>[];
  for (int i = 0; i < n; i++) {
    if (rgba[i * 4 + 3] < kMinAlpha || (mask != null && mask[i] == 0)) {
      continue;
    }
    samples
      ..add(rgba[i * 4].toDouble())
      ..add(rgba[i * 4 + 1].toDouble())
      ..add(rgba[i * 4 + 2].toDouble());
  }
  return Float64List.fromList(samples);
}

typedef _Extractor = Float64List Function(Uint8List rgba, {Uint8List? mask});

List<int> _rgb(dynamic value) =>
    <int>[for (final dynamic c in value as List<dynamic>) (c as num).toInt()];

List<int> _channels(ui.Color color) {
  // ignore: deprecated_member_use  (Color.value: universal across Flutter 3.19+)
  final int value = color.value;
  return <int>[(value >> 16) & 0xFF, (value >> 8) & 0xFF, value & 0xFF];
}

const Map<String, GarmentRegion> _regionByName = <String, GarmentRegion>{
  'upper': GarmentRegion.upper,
  'lower': GarmentRegion.lower,
};

void _expectPalette(
  List<ColorSample> got,
  List<dynamic> expectedColors,
  List<dynamic> expectedWeights,
  double atolRgb,
  double atolWeight,
  String label,
) {
  expect(got.length, expectedColors.length,
      reason: '$label: color count differs from Python: '
          '${got.map((ColorSample s) => s.hex).toList()} vs $expectedColors');
  for (int i = 0; i < expectedColors.length; i++) {
    final List<int> expectedRgb = _rgb(expectedColors[i]);
    final List<int> gotRgb = _channels(got[i].color);
    for (int d = 0; d < 3; d++) {
      expect(gotRgb[d], closeTo(expectedRgb[d], atolRgb),
          reason: '$label color $i: $gotRgb vs $expectedRgb');
    }
    expect(got[i].weight,
        closeTo((expectedWeights[i] as num).toDouble(), atolWeight),
        reason: '$label weight $i: ${got[i].weight} vs ${expectedWeights[i]}');
  }
}

/// The per-garment composition of `analyzeSegmentedFrame`, with the pixel
/// extractor injectable (engine path vs full-extraction control).
AnalysisResult _replayGarments(GarmentSegmentation guarded, Uint8List rgba,
    int width, int height, _Extractor extract) {
  final int frame = width * height;
  final List<GarmentPixels> regions = <GarmentPixels>[
    for (final GarmentRegion region in <GarmentRegion>[
      GarmentRegion.upper,
      GarmentRegion.lower
    ])
      if (guarded.maskFor(region) != null)
        GarmentPixels(
          region: region,
          pixels: extract(rgba, mask: guarded.maskFor(region)),
          pixelFraction: maskPixelCount(guarded.maskFor(region)!) / frame,
        ),
  ];
  return buildGarmentAnalysis(regions);
}

void _expectGarmentAnalysis(AnalysisResult res, Map<String, dynamic> expected,
    double atolRgb, double atolWeight, String label) {
  final Map<String, dynamic> prendas =
      expected['prendas'] as Map<String, dynamic>;
  expect(res.garments.length, prendas.length, reason: '$label garment count');
  for (final GarmentBlockData block in res.garments) {
    final String name = block.region == GarmentRegion.upper ? 'upper' : 'lower';
    final Map<String, dynamic> g = prendas[name] as Map<String, dynamic>;
    _expectPalette(block.palette, g['colores'] as List<dynamic>,
        g['pesos'] as List<dynamic>, atolRgb, atolWeight, '$label $name');
    expect(block.baseIndex, g['indice_base'] as int,
        reason: '$label per-garment base index of $name');
  }
  _expectPalette(
      res.palette,
      expected['colores'] as List<dynamic>,
      expected['pesos'] as List<dynamic>,
      atolRgb,
      atolWeight,
      '$label combined');
  expect(
    res.swatchRegions,
    <GarmentRegion>[
      for (final dynamic r in expected['regiones'] as List<dynamic>)
        _regionByName[r as String]!,
    ],
    reason: '$label swatch_regions attribution',
  );
  expect(res.baseIndex, expected['indice_base'] as int,
      reason: '$label global base index');
  if (res.baseIndex >= 0) {
    final List<int> expectedBase = _rgb(expected['base']);
    final List<int> gotBase = _channels(res.base!.color);
    for (int d = 0; d < 3; d++) {
      expect(gotBase[d], closeTo(expectedBase[d], atolRgb),
          reason: '$label global base color: $gotBase vs $expectedBase');
    }
    expect(
        res.baseBlock?.region, _regionByName[expected['region_base'] as String],
        reason: '$label owning region of the global base');
    expect(res.harmonies, hasLength(4));
  } else {
    expect(expected['region_base'], isNull);
    expect(res.harmonies, isEmpty);
    expect(res.canvasAccents, hasLength(5));
  }
}

void _expectProductAnalysis(AnalysisResult res, Map<String, dynamic> expected,
    double atolRgb, double atolWeight, String label) {
  _expectPalette(res.palette, expected['colores'] as List<dynamic>,
      expected['pesos'] as List<dynamic>, atolRgb, atolWeight, label);
  expect(res.baseIndex, expected['indice_base'] as int,
      reason: '$label base index');
  if (res.baseIndex >= 0) {
    final List<int> expectedBase = _rgb(expected['base']);
    final List<int> gotBase = _channels(res.base!.color);
    for (int d = 0; d < 3; d++) {
      expect(gotBase[d], closeTo(expectedBase[d], atolRgb),
          reason: '$label base color: $gotBase vs $expectedBase');
    }
    expect(res.harmonies, hasLength(4));
  } else {
    expect(res.harmonies, isEmpty);
  }
}

void main() {
  TestWidgetsFlutterBinding.ensureInitialized();
  final Map<String, dynamic> f = _load();

  group('real-size parity with colorlab — per-garment path (B2/F7)', () {
    for (final dynamic caseDyn in f['garment_cases'] as List<dynamic>) {
      final Map<String, dynamic> c = caseDyn as Map<String, dynamic>;
      final String name = c['nombre'] as String;
      final int height = c['height'] as int;
      final int width = c['width'] as int;
      final double atolRgb = (c['atol_rgb'] as num).toDouble();
      final double atolWeight = (c['atol_peso'] as num).toDouble();
      final Map<String, dynamic> expected =
          c['esperado'] as Map<String, dynamic>;

      test('$name: frame is real-size and the subsampling fires', () async {
        // The whole point of this fixture: ceil(n / 40k) > 1.
        expect(width * height, greaterThan(kMaxKmeansPixels));
        expect(
            width * height, lessThanOrEqualTo(kMaxDecodeSide * kMaxDecodeSide));
        final Uint8List rgba =
            await _decodePng(c['png_b64'] as String, width, height);
        _expectExactTransport(rgba, c['suma_canales'] as List<dynamic>);
        expect(extractRgbaPixels(rgba).length ~/ 3,
            lessThanOrEqualTo(kMaxKmeansPixels),
            reason: 'engine path must subsample a real-size frame');
        expect(_extractAll(rgba).length ~/ 3, width * height);
      });

      test('$name: mask stage is EXACT (split + erosion + guards)', () async {
        final Uint8List classMap = await _decodeClassMap(
            c['mapa_clases_png_b64'] as String,
            width,
            height,
            c['histograma_clases'] as List<dynamic>);
        final GarmentSegmentation guarded = applyGarmentGuards(
            MediaPipeGarmentSegmenter.buildMasks(classMap, width, height));
        final List<String> expectedRegions = <String>[
          for (final dynamic r
              in expected['regiones_supervivientes'] as List<dynamic>)
            r as String,
        ];
        expect(
            guarded.regions.toList(),
            <GarmentRegion>[
              for (final String r in expectedRegions) _regionByName[r]!
            ],
            reason: 'surviving regions differ from Python');
        final Map<String, dynamic> counts =
            expected['pixeles_region'] as Map<String, dynamic>;
        for (final String region in expectedRegions) {
          expect(maskPixelCount(guarded.maskFor(_regionByName[region]!)!),
              counts[region] as int,
              reason: 'eroded pixel count of $region differs from Python');
        }
      });

      if (c.containsKey('preproceso')) {
        // MediaPipe input-tensor parity (F7's second note): Dart `preprocess`
        // vs Python `preprocess_rgb` on the same real-size frame. The fixture
        // carries a strided sample (exact float32 values, atol 1e-5 covers the
        // double-vs-float32 accumulation order) plus the double-precision sum
        // of all 196,608 values (each side rounds to float32 first; a 0.05
        // slack is ~2x the worst-case rounding drift).
        test('$name: MediaPipe preprocess tensor matches Python', () async {
          final Map<String, dynamic> pp =
              c['preproceso'] as Map<String, dynamic>;
          final Uint8List rgba =
              await _decodePng(c['png_b64'] as String, width, height);
          final Float32List tensor =
              MediaPipeGarmentSegmenter.preprocess(rgba, width, height);
          expect(tensor.length, pp['longitud'] as int);
          final int stride = pp['stride'] as int;
          final List<dynamic> samples = pp['muestras'] as List<dynamic>;
          expect(samples.length, (tensor.length + stride - 1) ~/ stride);
          for (int k = 0; k < samples.length; k++) {
            expect(tensor[k * stride],
                closeTo((samples[k] as num).toDouble(), 1e-5),
                reason: 'tensor value ${k * stride}');
          }
          double sum = 0;
          for (final double v in tensor) {
            sum += v;
          }
          expect(sum, closeTo((pp['suma'] as num).toDouble(), 0.05),
              reason: 'tensor sum (bilinear sampling convention drift)');
        });
      }

      for (final MapEntry<String, _Extractor> variant in <String, _Extractor>{
        'engine path (subsampled, step from the whole frame)':
            extractRgbaPixels,
        'control (every mask pixel, as Python)': _extractAll,
      }.entries) {
        test('$name: ${variant.key}', () async {
          final Uint8List rgba =
              await _decodePng(c['png_b64'] as String, width, height);
          final Uint8List classMap = await _decodeClassMap(
              c['mapa_clases_png_b64'] as String,
              width,
              height,
              c['histograma_clases'] as List<dynamic>);
          final GarmentSegmentation guarded = applyGarmentGuards(
              MediaPipeGarmentSegmenter.buildMasks(classMap, width, height));
          final AnalysisResult res =
              _replayGarments(guarded, rgba, width, height, variant.value);
          _expectGarmentAnalysis(
              res, expected, atolRgb, atolWeight, variant.key);
        });
      }
    }
  });

  group('real-size parity with colorlab — product path (B2/F7)', () {
    for (final dynamic caseDyn in f['product_cases'] as List<dynamic>) {
      final Map<String, dynamic> c = caseDyn as Map<String, dynamic>;
      final String name = c['nombre'] as String;
      final int height = c['height'] as int;
      final int width = c['width'] as int;
      final double atolRgb = (c['atol_rgb'] as num).toDouble();
      final double atolWeight = (c['atol_peso'] as num).toDouble();
      final Map<String, dynamic> expected =
          c['esperado'] as Map<String, dynamic>;

      test('$name: #84 diagnostics (background estimate + drop fraction)',
          () async {
        expect(width * height, greaterThan(kMaxKmeansPixels));
        final Uint8List rgba =
            await _decodePng(c['png_b64'] as String, width, height);
        _expectExactTransport(rgba, c['suma_canales'] as List<dynamic>);
        final List<int> rgb = <int>[
          for (int i = 0; i < rgba.length; i += 4) ...<int>[
            rgba[i],
            rgba[i + 1],
            rgba[i + 2]
          ],
        ];
        final List<dynamic> expectedBg =
            expected['bg_colores'] as List<dynamic>;
        final List<List<int>> gotBg =
            estimateMultiedgeBackground(rgb, height, width);
        expect(gotBg.length, expectedBg.length,
            reason: 'multi-edge background color count: $gotBg vs $expectedBg');
        for (final dynamic e in expectedBg) {
          final List<int> expectedColor = _rgb(e);
          expect(
            gotBg.any((List<int> g) {
              for (int d = 0; d < 3; d++) {
                if ((g[d] - expectedColor[d]).abs() > atolRgb) {
                  return false;
                }
              }
              return true;
            }),
            isTrue,
            reason: 'background color $expectedColor not found in $gotBg',
          );
        }
        final List<bool> mask = productBackgroundMask(rgb, height, width);
        final double fraction = mask.where((bool d) => d).length / mask.length;
        // Same tolerance as product_mode_parity_test (K-means-derived rule).
        expect(fraction,
            closeTo((expected['frac_supresion'] as num).toDouble(), 0.02),
            reason: 'suppressed fraction');
      });

      test('$name: engine path (extractProductPixels, subsampled)', () async {
        final Uint8List rgba =
            await _decodePng(c['png_b64'] as String, width, height);
        final Float64List pixels = extractProductPixels(rgba, height, width);
        expect(pixels.length ~/ 3, lessThanOrEqualTo(kMaxKmeansPixels));
        final AnalysisResult res = buildResult(pixels, productMode: true);
        _expectProductAnalysis(res, expected, atolRgb, atolWeight, 'engine');
      });

      test('$name: control (every surviving pixel, as Python)', () async {
        final Uint8List rgba =
            await _decodePng(c['png_b64'] as String, width, height);
        final List<int> rgb = <int>[
          for (int i = 0; i < rgba.length; i += 4) ...<int>[
            rgba[i],
            rgba[i + 1],
            rgba[i + 2]
          ],
        ];
        final List<bool> drop = productBackgroundMask(rgb, height, width);
        final Uint8List keep = Uint8List(drop.length);
        for (int i = 0; i < drop.length; i++) {
          keep[i] = drop[i] ? 0 : 1;
        }
        final AnalysisResult res =
            buildResult(_extractAll(rgba, mask: keep), productMode: true);
        _expectProductAnalysis(res, expected, atolRgb, atolWeight, 'control');
      });
    }
  });
}
